### ISSUE TITLE
default of an argument

### ISSUE THREAD

**Issue by aminghrz** [jpvert/tigress#1]
hi
thanks for the codes
but there is a problem in the default of an argument of tigress() function.
the default of "usemulticore" should be F but it isn't and this error shows up:
> tigress(expdata = n1data)
Loading required package: parallel
Error in mclapply(seq(ntargets), stabselonegene, mc.cores = detectCores() -  : 
  'mc.cores' > 1 is not supported on Windows

but it works fine with "usemulticore = F"
another error shows up when allsteps = F:

> tigress(expdata = n1data,usemulticore = F,allsteps = F)
Error in edgepred[[nstepsLARS]] : subscript out of bounds

**Comment by jpvert** [comment]
Thanks for the comment. Both errors should be corrected in the new version.
